#include "main.h"

extern const byte puduris1[];
extern const byte puduris2[];
extern const byte niedres[];

const Frame apkaime[] = {
    { .img = puduris1, .x = 2,  .y = 14 },
    { .img = puduris1, .x = 5,  .y = 11 },
    { .img = puduris1, .x = 7,  .y = 22 },
    { .img = puduris1, .x = 10, .y = 10 },
    { .img = puduris1, .x = 16, .y = 8  },
    { .img = puduris1, .x = 18, .y = 4  },
    { .img = puduris1, .x = 22, .y = 18 },
    { .img = puduris2, .x = 0,  .y = 17 },
    { .img = puduris2, .x = 15, .y = 22 },
    { .img = puduris2, .x = 20, .y = 21 },
    { .img = puduris2, .x = 29, .y = 3  },
    { .img = puduris2, .x = 30, .y = 8  },
    { .img = puduris2, .x = 30, .y = 13 },
    { .img = niedres,  .x = 2,  .y = 19 },
    { .img = niedres,  .x = 7,  .y = 15 },
    { .img = niedres,  .x = 8,  .y = 14 },
    { .img = niedres,  .x = 8,  .y = 14 },
    { .img = niedres,  .x = 12, .y = 13 },
    { .img = niedres,  .x = 13, .y = 22 },
    { .img = niedres,  .x = 20, .y = 7  },
    { .img = niedres,  .x = 21, .y = 10 },
    { .img = niedres,  .x = 21, .y = 17 },
    { .img = niedres,  .x = 23, .y = 4  },
    { .img = niedres,  .x = 26, .y = 1  },
    { .img = niedres,  .x = 30, .y = 7  },
    { .img = niedres,  .x = 30, .y = 11 },
    { .img = niedres,  .x = 30, .y = 21 },
    { .img = NULL },
};

extern const byte egle1[];
extern const byte egle2[];
extern const byte egle3[];
extern const byte krasts[];

const Frame horizonts[] = {
    { .img = egle2,  .x = 0,  .y = 2  },
    { .img = egle3,  .x = 1,  .y = 2  },
    { .img = egle1,  .x = 2,  .y = 3  },
    { .img = egle2,  .x = 3,  .y = 2  },
    { .img = egle3,  .x = 4,  .y = 2  },
    { .img = egle2,  .x = 5,  .y = 2  },
    { .img = egle1,  .x = 6,  .y = 1  },
    { .img = egle3,  .x = 7,  .y = 2  },
    { .img = egle1,  .x = 8,  .y = 3  },
    { .img = egle2,  .x = 9,  .y = 2  },
    { .img = egle3,  .x = 10, .y = 2  },
    { .img = egle2,  .x = 11, .y = 2  },
    { .img = egle3,  .x = 12, .y = 2  },
    { .img = egle1,  .x = 13, .y = 3  },
    { .img = egle2,  .x = 14, .y = 2  },
    { .img = egle1,  .x = 15, .y = 1  },
    { .img = egle3,  .x = 16, .y = 2  },
    { .img = egle2,  .x = 17, .y = 2  },
    { .img = egle3,  .x = 18, .y = 2  },
    { .img = egle1,  .x = 19, .y = 3  },
    { .img = egle2,  .x = 20, .y = 2  },
    { .img = egle3,  .x = 21, .y = 2  },
    { .img = egle1,  .x = 22, .y = 3  },
    { .img = egle2,  .x = 23, .y = 2  },
    { .img = egle3,  .x = 24, .y = 2  },
    { .img = egle1,  .x = 25, .y = 3  },
    { .img = egle1,  .x = 26, .y = 3  },
    { .img = egle2,  .x = 27, .y = 2  },
    { .img = egle1,  .x = 28, .y = 1  },
    { .img = egle3,  .x = 29, .y = 2  },
    { .img = egle2,  .x = 30, .y = 2  },
    { .img = egle3,  .x = 31, .y = 2  },
    { .img = krasts, .x = 0,  .y = 13 },
    { .img = krasts, .x = 3,  .y = 13 },
    { .img = krasts, .x = 7,  .y = 13 },
    { .img = krasts, .x = 11, .y = 13 },
    { .img = krasts, .x = 13, .y = 13 },
    { .img = krasts, .x = 17, .y = 13 },
    { .img = krasts, .x = 18, .y = 13 },
    { .img = krasts, .x = 22, .y = 13 },
    { .img = krasts, .x = 25, .y = 13 },
    { .img = krasts, .x = 28, .y = 13 },
    { .img = NULL },
};

const Text tutorial[] = {
    { .x = 32, .y = 8,   .str = "Lai saglab`atu motiv`aciju iet cop`et," },
    { .x = 32, .y = 20,  .str = "katru dienu j`ano^ker lielais makans." },
    { .x = 32, .y = 48,  .str = "1. Valk`aties pa ezeru Q&0 A&1 O&2 P&3" },
    { .x = 32, .y = 60,  .str = "2. Izv`el`eties copes vietu SPACE" },
    { .x = 32, .y = 72,  .str = "3. Izurbt caurumu led`u O&2 P&3" },
    { .x = 32, .y = 84,  .str = "4. ^Gorg`at mormeni var ar SPACE" },
    { .x = 46, .y = 96,  .str = "Zivis ne^kersies, ja l`eni ~gorg`as" },
    { .x = 32, .y = 108, .str = "5. Lai piecirstu zivi j`aspie~z Q&0" },
    { .x = 32, .y = 120, .str = "6. Izvilkt zivi var spie~zot O&2 P&3" },
    { .x = 46, .y = 132, .str = "Velkot p`ar`ak `atri p`artr`uks aukla" },
    { .x = 46, .y = 144, .str = "Velkot p`ar`ak l`eni zivs aizies" },
    { .x = 32, .y = 172, .str = "Jo liek`aka zivs, jo tuv`ak t`a makanam" },
    { .str = NULL },
};
